# Generated by Django 3.0.10 on 2020-09-27 04:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listdefs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='consumers',
        ),
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.RemoveField(
            model_name='list',
            name='nodes',
        ),
        migrations.RemoveField(
            model_name='list',
            name='status',
        ),
        migrations.RemoveField(
            model_name='list',
            name='title',
        ),
        migrations.RemoveField(
            model_name='list',
            name='value',
        ),
        migrations.AddField(
            model_name='list',
            name='listdef',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
