# Generated by Django 3.0.10 on 2020-12-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0004_remove_nodetype_keyformat'),
        ('listdefs', '0002_list_validation_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='modeling.Schema'),
        ),
    ]
