# Generated by Django 3.0.10 on 2020-10-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0007_schema_description'),
        ('graphdefs', '0002_auto_20200926_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graphs', to='modeling.Schema'),
        ),
    ]
