# Generated by Django 3.0.10 on 2020-09-18 05:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('attributeSet', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('target', models.CharField(db_index=True, max_length=50)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='nodes.Node')),
            ],
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('node', 'type', 'target'), name='unique_edge'),
        ),
    ]
