# Generated by Django 3.0.10 on 2020-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_auto_20201003_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='related_nodes',
        ),
        migrations.AddField(
            model_name='node',
            name='target_nodes',
            field=models.ManyToManyField(related_name='source_nodes', through='nodes.Edge', to='nodes.Node'),
        ),
    ]
