# Generated by Django 3.0.10 on 2020-09-18 05:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
