# Generated by Django 3.0.10 on 2020-09-18 05:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edgetype',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('inheritsPairs', models.CharField(max_length=50, null=True)),
                ('pairs', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Nodetype',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('umlType', models.CharField(blank=True, max_length=50, null=True)),
                ('keyFormat', models.CharField(blank=True, max_length=50, null=True)),
                ('inherits', models.CharField(blank=True, max_length=50, null=True)),
                ('folder', models.CharField(max_length=50)),
            ],
        ),
    ]
