# Generated by Django 3.0.10 on 2020-10-14 14:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edgetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edgetype', models.CharField(max_length=50)),
                ('edgetype_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Nodetype',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('umlType', models.CharField(blank=True, max_length=50, null=True)),
                ('keyFormat', models.CharField(blank=True, max_length=50, null=True)),
                ('folder', models.CharField(max_length=50)),
                ('attribute_schema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodetypes', to='modeling.Schema')),
                ('target_nodetypes', models.ManyToManyField(related_name='source_nodetypes', through='modeling.Edgetype', to='modeling.Nodetype')),
            ],
        ),
        migrations.AddField(
            model_name='edgetype',
            name='source_nodetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_edgetypes', to='modeling.Nodetype'),
        ),
        migrations.AddField(
            model_name='edgetype',
            name='target_nodetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_edgetypes', to='modeling.Nodetype'),
        ),
        migrations.AddConstraint(
            model_name='edgetype',
            constraint=models.UniqueConstraint(fields=('source_nodetype', 'edgetype', 'target_nodetype'), name='unique_edgetype'),
        ),
    ]
