# Generated by Django 3.0.10 on 2020-10-18 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodetype',
            name='attribute_schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodetypes', to='modeling.Schema'),
        ),
    ]
