# Generated by Django 3.0.10 on 2020-09-25 10:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_auto_20200925_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
