# Generated by Django 3.0.10 on 2020-09-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_auto_20200925_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgetype',
            name='inheritsPairs',
        ),
        migrations.RemoveField(
            model_name='edgetype',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='edgetype',
            name='pairs',
        ),
        migrations.RemoveField(
            model_name='edgetype',
            name='purpose',
        ),
    ]
