# Generated by Django 3.0.10 on 2020-11-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_auto_20201105_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodetype',
            name='keyFormat',
        ),
    ]
