# Generated by Django 3.0.10 on 2020-10-01 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0004_auto_20200930_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodetype',
            name='inherits',
        ),
        migrations.AddField(
            model_name='nodetype',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodetypes', to='modeling.Schema'),
        ),
    ]
