# Generated by Django 3.0.10 on 2020-10-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0005_auto_20201001_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodetype',
            old_name='schema',
            new_name='attribute_schema',
        ),
    ]
