# Generated by Django 3.0.10 on 2020-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0006_auto_20201012_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
